cpo_front_end:
  ros__parameters:
    from_serial: false
    log_serial: false

    # if not from_serial, this gives the binary file to get the RTCM data
    # NOTE: will likely need to replace path with your file paths
#    data_path: "~/ASRL/data/feb10/rtcm3/feb10d.BIN"
    data_path: "~/ASRL/vtr3/main/src/deps/cpo/cpo_frontend/data/rtcm3/feb15c.BIN"

    # Unix time data is from. Set to negative to use live time
#    approximate_time: 1612990000       # Feb.10/21
    approximate_time: 1613400000       # Feb.15/21
    #    approximate_time: -1       # now
    use_sim_time: true

    enable_tropospheric_correction: true