cpo_front_end:
  ros__parameters:
    from_serial: false
    log_serial: false

    # if not from_serial, this gives the binary file to get the RTCM data
    # NOTE: will likely need to replace path with your file paths
    data_path: "~/cpo_workspace/src/cpo/cpo_frontend/data/rtcm3/feb15c.BIN"

    # Unix time data is from. Set to negative to use live time
    approximate_time: 1613400000       # Feb.15/21
    #    approximate_time: -1       # now
    use_sim_time: true

    enable_tropospheric_correction: true