cpo_front_end:
  ros__parameters:
    from_serial: false
    log_serial: false

    # if not from_serial, this gives the binary file to get the RTCM data
    # NOTE: will likely need to replace path with your file paths
#    data_path: "~/ASRL/data/feb10/rtcm3/feb10d.BIN"
    data_path: "~/ASRL/vtr3/main/src/deps/cpo/cpo_frontend/data/rtcm3/feb15c.BIN"

    # Unix time data is from. Set to negative to use live time
#    approximate_time: 1612990000       # Feb.10/21
    approximate_time: 1613400000       # Feb.15/21
    #    approximate_time: -1       # now
    use_sim_time: true

    enable_tropospheric_correction: true

    # DROPOUT EXPERIMENTS...
#    start_time: 1613417000
#    end_time: 1613417270
#    start_drop_time: 1613417122   # feb15a
#    end_drop_time: 1613417177
#    start_drop_time: 1613419680   # feb15c
#    end_drop_time: 1613419735
#    start_drop_time: 1613424673   # feb15e
#    end_drop_time: 1613424728
#    start_drop_time: 1613425927   # feb15f
#    end_drop_time: 1613425982
#    drop_max_sats: 3
